apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iam-go

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - nats.yaml
  - auth.yaml
  - user.yaml
  - gateway.yaml
  - ingress.yaml
  - networkpolicy.yaml

images:
  - name: iam-go-auth
    newTag: latest
  - name: iam-go-user
    newTag: latest
  - name: iam-go-gateway
    newTag: latest
